import { server_port } from "../component/api";


export const chatbgImage = [
    server_port + "/chatBG/chatbg.jpg",
    server_port + "/chatBG/chatbg.gif",
    server_port + "/chatBG/chatbg2.gif",
    server_port + "/chatBG/chatbg3.gif",
    server_port + "/chatBG/chatbg4.avif",
    server_port + "/chatBG/chatbg5.avif",
    server_port + "/chatBG/chatbg6.avif",
    server_port + "/chatBG/chatbg7.avif",
    server_port + "/chatBG/chatbg8.avif",
    server_port + "/chatBG/chatbg9.avif",
    server_port + "/chatBG/chatbg10.avif",
    server_port + "/chatBG/chatbg11.avif",
    server_port + "/chatBG/chatbg12.avif",
    server_port + "/chatBG/chatbg13.avif",
    server_port + "/chatBG/chatbg14.avif",
    server_port + "/chatBG/chatbg15.avif",
    server_port + "/chatBG/chatbg16.avif",
    server_port + "/chatBG/chatbg17.avif",
    server_port + "/chatBG/chatbg18.avif",
    server_port + "/chatBG/chatbg19.avif",
    server_port + "/chatBG/chatbg20.avif",
    server_port + "/chatBG/chatbg21.avif",
    server_port + "/chatBG/chatbg22.avif",
    server_port + "/chatBG/chatbg23.avif",
    server_port + "/chatBG/chatbg24.avif",
    server_port + "/chatBG/chatbg25.avif",
    server_port + "/chatBG/chatbg26.avif",
    server_port + "/chatBG/chatbg27.avif",
    server_port + "/chatBG/chatbg28.avif",
    server_port + "/chatBG/chatbg29.avif",
    server_port + "/chatBG/chatbg30.avif",
    server_port + "/chatBG/chatbg31.avif",
    server_port + "/chatBG/chatbg32.avif",
    server_port + "/chatBG/chatbg33.avif",
    server_port + "/chatBG/chatbg34.avif",
    server_port + "/chatBG/chatbg35.avif",
    server_port + "/chatBG/chatbg36.avif",
    server_port + "/chatBG/chatbg38.avif"
];
